project:
  type: website
  output-dir: docs
  resources:
    - Special_assignment_Emma_Kuutti_final.pdf
    - Emma_Kuutti_Biomedical_Engineering_CV.pdf

website:
  title: "Emma Kuutti | Biomedical Engineer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About works
      - href: projects.qmd
        text: Projects
        menu:
          - href: Special_assignment_Emma_Kuutti_final.pdf
            text: "Special assignment for my master's degree in biomedical engineering"
          - href: project.ipynb
            text: "Mathematical modelling of brain tumor growth on 2D -course work for computational physics course"
      - href: "https://aaltodoc.aalto.fi/server/api/core/bitstreams/f163af85-4a6e-4327-92b7-b7c707ef9a86/content"
        text: Bachelor's Thesis      
      - href: Emma_Kuutti_Biomedical_Engineering_CV.pdf
        text: CV  
      
      


format:
  html:
    theme:
      - Minty
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow">




