project:
  type: website
  output-dir: docs

website:
  title: "Emma Kuutti | Biomedical Engineer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About works
      - href: projects.qmd
        text: Projects
        menu:
          - href: project.ipynb
            text: "Mathematical modelling of brain tumor growth on 2D -course work for computational physics course"
      - href: bachelor_Kuutti_Emma_2025.pdf 
        text: Bachelor's Thesis      
      - href: Emma_Kuutti_Biomedical_Engineering_CV.pdf
        text: CV  
      
      


format:
  html:
    theme:
      - Minty
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow">




